name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install flutter sdk
      run: |
        git clone https://github.com/flutter/flutter.git -b beta
        export PATH="$PATH:`pwd`/flutter/bin"
        flutter doctor
        
    - name: Install go sdk
      run: |
        wget -c https://dl.google.com/go/go1.14.4.linux-amd64.tar.gz -O - | sudo tar -xz -C /usr/local
        export PATH=$PATH:/usr/local/go/bin
        
    - name: Install hover
      run: |
        sudo apt-get update
        sudo apt-get install gcc libc6-dev libgl1-mesa-dev xorg-dev
        GO111MODULE=on go get -u -a github.com/go-flutter-desktop/hover
    
    - name: Build project
      run: |
        export PATH="$PATH:`pwd`/flutter/bin"
        export PATH="$PATH:`go env GOPATH`/bin"
        flutter pub get
        hover build linux
        
    - name: Run tests
      run: |
        export CODECOV_TOKEN="1249b809-5297-4530-828c-4da44a3cd7de"
        ./flutter/bin/flutter test --coverage
        bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info

